# Generated by Django 4.2 on 2023-04-28 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Linkn',
            new_name='Link',
        ),
    ]
